/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoxesBaseRouteImport } from './routes/boxes/$base'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as BoxesBaseImportRouteImport } from './routes/boxes/$base_.import'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as BoxesBaseAppsAppRouteImport } from './routes/boxes/$base_.apps.$app'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBaseRoute = BoxesBaseRouteImport.update({
  id: '/boxes/$base',
  path: '/boxes/$base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBaseImportRoute = BoxesBaseImportRouteImport.update({
  id: '/boxes/$base_/import',
  path: '/boxes/$base/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBaseAppsAppRoute = BoxesBaseAppsAppRouteImport.update({
  id: '/boxes/$base_/apps/$app',
  path: '/boxes/$base/apps/$app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/boxes/$base/import': typeof BoxesBaseImportRoute
  '/boxes/$base/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/boxes/$base/import': typeof BoxesBaseImportRoute
  '/boxes/$base/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/boxes/$base_/import': typeof BoxesBaseImportRoute
  '/boxes/$base_/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/boxes/$base'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/boxes/$base/import'
    | '/boxes/$base/apps/$app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/boxes/$base'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/boxes/$base/import'
    | '/boxes/$base/apps/$app'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/callback'
    | '/boxes/$base'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/boxes/$base_/import'
    | '/boxes/$base_/apps/$app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BoxesBaseRoute: typeof BoxesBaseRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  BoxesBaseImportRoute: typeof BoxesBaseImportRoute
  BoxesBaseAppsAppRoute: typeof BoxesBaseAppsAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$base': {
      id: '/boxes/$base'
      path: '/boxes/$base'
      fullPath: '/boxes/$base'
      preLoaderRoute: typeof BoxesBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$base_/import': {
      id: '/boxes/$base_/import'
      path: '/boxes/$base/import'
      fullPath: '/boxes/$base/import'
      preLoaderRoute: typeof BoxesBaseImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$base_/apps/$app': {
      id: '/boxes/$base_/apps/$app'
      path: '/boxes/$base/apps/$app'
      fullPath: '/boxes/$base/apps/$app'
      preLoaderRoute: typeof BoxesBaseAppsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BoxesBaseRoute: BoxesBaseRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  BoxesBaseImportRoute: BoxesBaseImportRoute,
  BoxesBaseAppsAppRoute: BoxesBaseAppsAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
